config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 9).order('created_at DESC')
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 9)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 9).order('created_at DESC')
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || (logged_in? and !current_user.admin?)
        flash[:danger] = "Only admins can perform that action"
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Login information did not match"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 9)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 9)
  end

  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only admin users can perform that action"
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.haml
- obj.each do |article|
  .col-xs-10.col-xs-offset-1.col-md-4{ class:[ ("col-md-offset-4" if obj.length == 1),
                                              ("col-md-offset-0" if obj.length != 1)]}
    .well.article
      %h4
        = link_to truncate(article.title, length: 28), article_path(article)
      %div
        .article-description= truncate(article.description, length: 100)
        .article-details
          - if article.categories.length == 1
            = render article.categories[0]
          - if article.categories.length > 1
            = render article.categories[0, 2]
          - if article.categories.length > 2
            %span ...
          %div{ class:("margin-t10" if article.categories.any?)}
            %small.text-muted
              Created by #{link_to article.user.username, user_path(article.user) if article.user}
              #{time_ago_in_words(article.created_at)} ago
              %br/
              Last updated: #{time_ago_in_words(article.updated_at)} ago
      - if logged_in? && (current_user == article.user || current_user.admin?)
        .article-actions
          = link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe,
            edit_article_path(article),
            class: "btn btn-default btn-sm",
            "data-placement" => "top",
            "data-toggle" => "tooltip",
            :title => "Edit"
          = link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe,
            article_path(article),
            method: :delete,
            data: { confirm: "Are you sure you want to delete the article?"},
            class: "btn btn-default btn-sm",
            "data-placement" => "top",
            "data-toggle" => "tooltip",
            :title => "Delete"

app/views/articles/_form.html.haml
= render 'shared/errors', obj: @article
.row.margin-t30
  = form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f|
    .form-group
      .control-label.col-sm-3.text-right
        = f.label :title
        %br/
      .col-sm-7
        = f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true
    .form-group
      .control-label.col-sm-3.text-right
        = f.label :description
        %br/
      .col-sm-7
        = f.text_area :description, rows: 7, class: "form-control", placeholder: "Body of article"
    .form-group
      .col-sm-7.col-sm-offset-3
        = f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|
          - cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text}
    .form-group
      .col-sm-7.col-sm-offset-3
        = f.submit class: "btn btn-primary"
        = link_to "Cancel", articles_path, class: "btn btn-link"

app/views/articles/edit.html.haml
.text-center
  %h1 Edit existing article
= render 'form'

app/views/articles/index.html.haml
%h1.text-center All Articles
.text-center
  = will_paginate
.row.margin-t10{ class:("margin-t30" if @articles.length <= 9) }
  = render 'article', obj: @articles
.text-center
  = will_paginate

app/views/articles/new.html.haml
.text-center
  %h1 Create New Article
= render 'form'

app/views/articles/show.html.haml
.row
  - if @article.user
    .col-xs-8.col-xs-offset-2
      .text-center
        .small.text-muted Created by
        = link_to gravatar_for(@article.user), user_path(@article.user), class: "margin-t10"
        %h4= link_to @article.user.username, user_path(@article.user)
  .well.col-xs-8.col-xs-offset-2.margin-t30
    %h2= @article.title
    %hr/
    = simple_format(@article.description)
    - if @article.categories.any?
      = render @article.categories
  .col-xs-8.col-xs-offset-2
    - if logged_in? && (current_user == @article.user || current_user.admin?)
      = link_to "Edit", edit_article_path(@article), class: "btn btn-link"
      = link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-link"
    = link_to "View all articles", articles_path, class: "btn btn-link"

app/views/categories/_category.html.haml
%span.category.margin-r10= link_to category.name, category_path(category)

app/views/categories/_form.html.haml
= render 'shared/errors', obj: @category
.row.margin-t30
  = form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f|
    .form-group
      .control-label.col-sm-3.text-right
        = f.label :name
      .col-sm-7
        = f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true
    .form-group
      .col-sm-7.col-sm-offset-3
        = f.submit class: "btn btn-primary"
        = link_to "Cancel", articles_path, class: "btn btn-link"

app/views/categories/edit.html.haml
%h1.text-center Edit Category Name
= render 'form'

app/views/categories/index.html.haml
%h1.text-center All Categories
.text-center
  = will_paginate
.row.margin-t10{ class:("margin-t30" if @categories.length <= 9) }
  - @categories.each do |category|
    .col-xs-10.col-xs-offset-1.col-md-4{ class:[ ("col-md-offset-4" if @categories.length == 1),
                                              ("col-md-offset-0" if @categories.length != 1)]}
      .well.well-sm.text-center
        %h4= link_to "#{category.name}", category_path(category)
        %small
          = pluralize(category.articles.count, "article")
.text-center
  = will_paginate

app/views/categories/new.html.haml
%h1.text-center Create New Category
= render 'form'

app/views/categories/show.html.haml
%h1.text-center= "Category: " + @category.name
- if logged_in? and current_user.admin?
  .text-center= link_to "Edit Category Name", edit_category_path(@category)
%h5.text-center.text-muted
  There are #{ pluralize(@category.articles.count, "article") } in this category
.text-center
  = will_paginate @category_articles
.row.margin-t10{ class:("margin-t30" if @category_articles.length <= 9) }
  = render 'articles/article', obj: @category_articles
.text-center
  = will_paginate @category_articles

app/views/layouts/_footer.html.haml
.container
  %footer.footer
    %small
      Exercise from
      %a{:href => "https://www.udemy.com/the-complete-ruby-on-rails-developer-course/", :target => "_blank"} The Complete Ruby on Rails Developer Course
      implemented by
      %a{:href => "http://www.renancastro.com", :target => "_blank"} Renan Castro
    %nav
      %ul
        %li
          %a{ :href => "https://github.com/renandf/udemy-rails-alpha-blog", :target => "_blank"} Project on Github

app/views/layouts/_messages.html.haml
.row
  .col-xs-10.col-xs-offset-1
    - flash.each do |name, msg|
      %div{:class => "alert alert-#{"#{name}"}"}
        %a.close{"data-dismiss" => "alert", :href => "#"} ×
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      / <a class="navbar-brand" href="#">Brand</a>
      = link_to "Alpha Blog", root_path, class: "navbar-brand text-uppercase", id: "logo"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        / <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        %li= link_to "Articles", articles_path
        %li= link_to "Users", users_path
        - if logged_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Actions
              %span.caret
            %ul.dropdown-menu
              %li= link_to "New Article", new_article_path
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Separated link
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} One more separated link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Categories
            %span.caret
          %ul.dropdown-menu
            %li= link_to "All Categories", categories_path
            %li.divider{:role => "separator"}
            - Category.all.each do |category|
              %li= link_to "#{category.name}", category_path(category)
            - if logged_in? and current_user.admin?
              %li.divider{:role => "separator"}
              %li
                = link_to "Create New Category", new_category_path
      %form.navbar-form.navbar-left{:role => "search"}
        .form-group
          %input.form-control{:placeholder => "Search", :type => "text"}/
        %button.btn.btn-default{:type => "submit"} Submit
      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          %li
            = link_to 'Log out', logout_path, method: :delete
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Profile
                - if current_user.admin?
                  (Admin)
                %span.caret
              %ul.dropdown-menu
                %li= link_to "Edit Profile", edit_user_path(current_user)
                %li= link_to "View Profile", user_path(current_user)
        - else
          %li
            = link_to 'Log in', login_path
          %li
            = link_to 'Sign up', signup_path
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{"name" => "viewport", :content => "width=device-width, initial-scale=1" }/
    %title AlphaBlog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    .container
      = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?

app/views/pages/home.html.haml
.jumbotron.text-center
  %h1 Alpha Blog
  %p.margin-t30
    This is an exercise from
    %a{:href => "https://www.udemy.com/the-complete-ruby-on-rails-developer-course/", :target => "_blank"} The Complete Ruby on Rails Developer Course
    on
    %a{:href => "https://www.udemy.com/", :target => "_blank"} Udemy.
    The goal was to create an application where you can create simple articles containing title and description, add categories to those articles and be able to edit or delete your own.
  %p
    You can view the
    %a{ :href => "https://github.com/renandf/udemy-rails-alpha-blog", :target => "_blank"} Project on Github
    to see details on how it was coded.
  %p
    You're welcome to sign up and create some fake articles to see how it works, or simply use the top navigation to check it without signing up. If you have a
    %a{:href => "https://en.gravatar.com/", :target => "_blank"} Gravatar
    account, your picture will be grabbed from there.
  = link_to "Create a test account", signup_path, class: "btn btn-primary btn-lg margin-t30"

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .row
    .col-xs-10.col-xs-offset-2
      .panel.panel-danger
        .panel-heading
          %h2.panel-title
            = pluralize(obj.errors.count, "error")
            prohibited this article from being saved:
          .panel-body
            %ul
              - obj.errors.full_messages.each do |msg|
                %li= msg

app/views/users/_form.html.haml
= render 'shared/errors', obj: @user
.row.margin-t30
  = form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f|
    .form-group
      .control-label.col-sm-3.text-right
        = f.label :username
      .col-sm-7
        = f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true
    .form-group
      .control-label.col-sm-3.text-right
        = f.label :email
      .col-sm-7
        = f.email_field :email, class: "form-control", placeholder: "Enter email"
    .form-group
      .control-label.col-sm-3.text-right
        = f.label :password
      .col-sm-7
        = f.password_field :password, class: "form-control", placeholder: "Enter password"
    .form-group
      .col-sm-7.col-sm-offset-3
        = f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary")
        = link_to "Cancel", articles_path, class: "btn btn-link"

app/views/users/edit.html.haml
.text-center
  %h1 Edit your account
= render 'form'

app/views/users/index.html.haml
%h1.text-center All Alpha Bloggers
.text-center
  = will_paginate
.row.margin-t10{ class:("margin-t30" if @users.length <= 9) }
  - @users.each do |user|
    .col-xs-10.col-xs-offset-1.col-md-4{ class:[ ("col-md-offset-4" if @users.length == 1),
                                              ("col-md-offset-0" if @users.length != 1)]}
      .well.text-center
        = link_to gravatar_for(user), user_path(user)
        %h4
          = link_to user.username, user_path(user)
        %small
          = pluralize(user.articles.count, "article") if user.articles
        - if logged_in? and current_user.admin?
          .article-actions
            = link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe,
              user_path(user), method: :delete,
              data: { confirm: "Are you sure you want to delete the user and all their articles?"},
              class: "btn btn-default btn-sm"
.text-center
  = will_paginate

app/views/users/new.html.haml
.text-center
  %h1 Sign up for Alpha Blog
= render 'form'

app/views/users/show.html.haml
.row
  .col-md-4.col-md-offset-4.text-center
    = gravatar_for @user, size: 150
%h1.text-center
  Welcome to #{ @user.username }'s page
%h5.text-center.text-muted
  #{ @user.username } wrote #{ pluralize(@user.articles.count, "article") }
.text-center
  = will_paginate @user_articles
.row.margin-t10{ class:("margin-t30" if @user_articles.length <= 9) }
  = render 'articles/article', obj: @user_articles
.row
  .col-md-12.text-center
    = will_paginate @user_articles